export const quotes = [
    'A budget is telling your money where to go, instead of wondering where it went.',
    'Beware of little expenses; a small leak will sink a great ship.',
    'Do not save what is left after spending, but spend what is left after saving.',
    'The habit of saving is itself an education.',
    'Frugality includes all the other virtues.',
    'A penny saved is a penny earned.',
    "Save a little money each month, and at the end of the year, you'll be surprised at how little you have.",
    "It's not your salary that makes you rich; it's your spending habits.",
    'The quickest way to double your money is to fold it in half and put it back in your pocket.',
    'Money looks better in the bank than on your feet.',
    'Spend less than you earn, and invest the rest wisely.',
    "If you buy things you don't need, you will soon sell things you need.",
    'He who buys what he does not need steals from himself.',
    'The art is not in making money but in keeping it.',
    'Money grows on the tree of patience.',
    'A fool and his money are soon parted.',
    "It's good to have money and the things that money can buy, but it's good to check up once in a while to make sure you haven't lost the things money can't buy.",
    'Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.',
    'You must gain control over your money, or the lack of it will forever control you.',
    "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.",
    'An investment in knowledge pays the best interest.',
    'The best way to save money is not to lose it.',
    'Don’t tell me where your priorities are. Show me where you spend your money, and I’ll tell you what they are.',
    'Do not save what is left after spending, but spend what is left after saving.',
    'Wealth consists not in having great possessions, but in having few wants.',
    'Balancing your money is the key to having enough.',
    'Do not underestimate the value of doing nothing.',
    'A wise person should have money in their head, but not in their heart.',
    'The more you learn, the more you earn.',
    'Happiness is not in the mere possession of money; it lies in the joy of achievement.',
    'Money often costs too much.',
    'Don’t go broke trying to look rich.',
    "Spend your money on the things that money can't buy: love, health, and happiness.",
    'The way to wealth is as plain as the way to market.',
    "You can be young without money, but you can't be old without it.",
    'Live like no one else, so later you can live like no one else.',
    'Rich people stay rich by living like they are broke.',
    'Saving is a fine thing. Especially when your parents have done it for you.',
    'Debt is like any other trap; easy enough to get into, but hard enough to get out of.',
    'Never spend your money before you have it.',
    'Without frugality, none can be rich, and with it, very few would be poor.',
    'You don’t have to be smarter than the next person; you have to be more disciplined.',
    'Do not save what is left after spending, but spend what is left after saving.',
    'The stock market is a device for transferring money from the impatient to the patient.',
    "If saving money is wrong, I don't want to be right.",
    'It’s not how much money you make, but how much money you keep.',
    'Riches are not an end of life, but an instrument of life.',
    'It is not the man who has too little, but the man who craves more, that is poor.',
    'Too many people spend money they haven’t earned, to buy things they don’t want, to impress people they don’t like.',
    'The desire of gold is not for gold. It is for the means of freedom and benefit.',
    'Every time you borrow money, you’re robbing your future self.',
    'Spend less than you earn, invest the rest, and avoid debt.',
    'Invest in yourself—it pays the best dividends.',
    'Be fearful when others are greedy and greedy when others are fearful.',
    'The rich invest in time; the poor invest in money.',
    'Do not let your spending overtake your savings.',
    'Learn to manage your money, or the lack of it will manage you.',
    'Do not spend more than you earn—it’s a simple rule with big consequences.',
    'A goal without a plan is just a wish.',
    'Money is a terrible master but an excellent servant.',
    'Don’t let making a living prevent you from making a life.',
    'The real measure of your wealth is how much you’d be worth if you lost all your money.',
    'It’s not the man who has too little, but the man who craves more, that is poor.',
    'You can’t have everything you want, but you can have the things that really matter.',
    'When you understand that your self-worth is not defined by your net worth, then you’ll have financial freedom.',
    'True financial freedom is achieved by living below your means and building wealth.',
    'The more money you make, the more you need to learn to manage it.',
    'Wealth is not about having a lot of money; it’s about having a lot of options.',
    'Stop chasing money and start chasing freedom.',
    'Never let the fear of losing be greater than the excitement of winning.',
    'The secret to saving is spending wisely.',
    'Being frugal doesn’t mean being cheap. It means being resourceful.',
    "Don't watch the clock; do what it does. Keep going—and keep saving.",
    'Money is a great servant but a terrible master.',
    'The best investment you can make is in yourself.',
    'It’s not just about saving money; it’s about creating the life you want.',
];
